# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/configuration-reference
version: 2.1

# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/configuration-reference/#jobs
jobs:
  test-linux-intel:
    docker:
      - image: cimg/base:stable
    resource_class: small
    steps:
      - checkout
      - run:
          name: "Install Clang"
          command: "sudo apt-get update && sudo apt-get install clang"
      - run:
          name: "Test All"
          command: "make test_all && ./build/test_all"
  test-linux-arm:
    docker:
      # TODO(ambrus): This should be an ARM image but I can't find any.
      - image: cimg/base:stable
    resource_class: arm.medium
    steps:
      - checkout
      - run:
          name: "Install Clang"
          command: "sudo apt-get update && sudo apt-get install clang"
      - run:
          name: "Test All"
          command: "make test_all && ./build/test_all"
  test-mac-intel:
    macos:
      xcode: 15.0.0
    resource_class: macos.x86.medium.gen2
    steps:
      - checkout
      - run:
          name: "Test All"
          command: "make test_all && ./build/test_all"
  test-mac-arm:
    macos:
      xcode: 15.0.0
    resource_class: macos.m1.medium.gen1
    steps:
      - checkout
      - run:
          name: "Test All"
          command: "make test_all && ./build/test_all"
  build-emscripten:
    docker:
      - image: cimg/base:stable
    resource_class: small
    steps:
      - checkout
      - run:
          name: "Install Emscripten"
          command: "git clone https://github.com/emscripten-core/emsdk.git && cd emsdk && ./emsdk install latest && ./emsdk activate latest"
      - run:
          name: "Build Tests"
          command: "source emsdk/emsdk_env.sh && WASM=1 make test_all && ./build/test_all"

# Orchestrate jobs using workflows
# See: https://circleci.com/docs/configuration-reference/#workflows
workflows:
  test-all-workflow:
    jobs:
      - test-linux-intel
      # - test-linux-arm   # Can't find Docker image for ARM.
      - test-mac-intel
      # - test-mac-arm  # Not available in pricing plan? Sent email.
      - build-emscripten
