# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/configuration-reference
version: 2.1

# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/configuration-reference/#jobs
jobs:
  test-linux:
    docker:
      - image: cimg/base:stable
    resource_class: small
    steps:
      - checkout
      - run:
          name: "Install Clang"
          command: "sudo apt-get update && sudo apt-get install clang"
      - run:
          name: "Test All"
          command: "make test_all && ./build/test_all"
  test-mac-intel:
    macos:
      - xcode: "15.0.0"
    resource_class: macos.x86.medium.gen2
    steps:
      - checkout
      - run:
          name: "Test All"
          command: "make test_all && ./build/test_all"

resource_class: macos.x86.medium.gen2

# Orchestrate jobs using workflows
# See: https://circleci.com/docs/configuration-reference/#workflows
workflows:
  test-all-workflow:
    jobs:
      - test-linux
      - test-mac-intel
